This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./Thesis_Tosi.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Thesis_Tosi.acn....done (419 entries accepted, 0 rejected).
Sorting entries......done (3858 comparisons).
Generating output file Thesis_Tosi.acr....done (261 lines written, 0 warnings).
Output written in Thesis_Tosi.acr.
Transcript written in Thesis_Tosi.alg.
