This is makeindex, version 2.17 [TeX Live 2024] (kpathsea + Thai support).
Scanning style file ./Thesis_Tosi.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Thesis_Tosi.acn....done (486 entries accepted, 0 rejected).
Sorting entries.......done (4643 comparisons).
Generating output file Thesis_Tosi.acr....done (289 lines written, 0 warnings).
Output written in Thesis_Tosi.acr.
Transcript written in Thesis_Tosi.alg.
